opt_in_rules: # some rules are only opt-in
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing

disabled_rules: # rule identifiers to exclude from running
  - function_body_length
  - trailing_whitespace
  - force_cast
  - type_name
  - file_length
  - type_body_length
  - cyclomatic_complexity
  - identifier_name
  - line_length

excluded: # paths to ignore during linting. overridden by `included`.
  - Pods
  - Carthage
  - fastlane
